### PR TITLE
PR: Prepare for cutting Spyder 4 branch with more maintainable structure, updating docs, upgrading build infra and adding basic pre-commit fixers

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

While this involves a number of backend changes, none should have any effect on the content or appearance of the docs themselves (aside from some syntax bugfixes, and the URL change for lower-level docs).

* The number of docs of different types has long overwhelmed what's usable in a single flat source directory and URL structure, becoming unweildly to navigate, develop and maintain. Therefore, as has been planned for a while now, this PR organizes the docs into sub-directories that match the menu structure, making it much easier to keep things organized, find what one is looking for and avoid name collisions, while keeping the most popular docs and those linked from the outside at the root. This will allow the number and types of docs to continue to grow with Spyder 5 without having to worry about merge conflicts or ever-increasing bloat. As part of this, I've fixed all the internal links and toctrees  and make them more robust, so that if we move docs around in the future, they'll continue to work.
* Added pre-commit locally and on the CIs to automatically detect, and in most cases fix, basic syntax (reST, Python, JSON, TOML, XML, YAML, etc), lint (e.g. common reST mistakes) and style issues (mixed EoLs, mixed tabs/spaces, missing EoF, trailing whitespace, etc). This will avoid most merge conflicts between `4.x` and `master` and catch (and often fix) many common issues that would otherwise come up in the review stage. I've also fixed the outstanding issues pre-commit identified, mostly automatic style/lint things plus some actual reST errors.
* Upgraded to the build system to make it faster, more reliable and more maintainable, as well as prep for the `4.x` branching, and bumped deps
* Updated the Readme and Contributing guide to correct out of date info/badges, add more descriptive and easier to use install instructions, and add pre-commit and other helpers.
* Updated the .gitattributes to the latest upstream version

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
To make a long story short, this ended up being much more extensive than anticipated, but I ended up doing a number of things we've been planning for a long time (pre-commit integration, organizing the source directory and URLs, organizing the assets/static directories, and re-conforming the docs to the standard style), plus some routine maintenance that had been deferred (build system, deps, gitattributes, updating the readme to reflect the docs' official release) and general improvements to ease of building, development, and maintenance.

Once this is merged and deploys successfully, all that I'll need to do to complete the full setup for separate Spyder 4 and 5 branches is simply cut and push the `4.x` branch, and then merge a simple PR to `master` (that I already have a draft of locally) that will bump the version in the appropriate places and trigger a rebuild to include the new separate `4.x` branch.

**Comment by CAM-Gerlach** [comment]
Per request from @ccordoba12 , going ahead and merging this one, so we can provide with branching and bumping the version in `master`.

**Comment by CAM-Gerlach** [comment]
And per @juanis2112 as well

**Comment by CAM-Gerlach** [comment]
@juanis2112 (and @ccordoba12 + @dalthviz , if you'll be contributing as well), make sure pre-commit is installed in your active environment and run `pre-commit install && pre-commit install -t commit-msg` from anywhere in the repo, which will install the hooks. They are mostly the same ones as you already have installed for the theme and website, but some of the versions are bumped and there are a few new ones (basic reST and Python checks).

This will automatically detect, and and most cases fix the majority of common issues for you whenever you commit, which will help avoid many common errors, deal with most of the more nitpicky review comments and issues, and help avoid merge conflicts between `4.x` and `master`. Thanks.

**Comment by juanis2112** [comment]
Thanks @CAM-Gerlach

**Pull request merged**
