### PR TITLE
Add warning about only loading .spydata files from trusted sources

### LINKED ISSUE #328: Add warning not to import untrusted data in Variable Explorer
# Issue Report

## Issue Description

Importing untrusted data in the variable explorer is unsafe because it uses pickle which executes arbitrary code. Users should be warned against this.

### Where is the relevant portion of the documentation located?

Second line of https://github.com/spyder-ide/spyder-docs/blob/master/doc/panes/variableexplorer.rst#toolbar-buttons

### What would you suggest it be replaced with?

Add a warning.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

    * [x] N/A
    * [ ] Spyder 5 (``master``)
    * [ ] Spyder 4 (``4.x``)
    * [ ] Spyder 3 (``3.x``, frozen)

* Are you planning on submitting a Github pull request with a suitable change?

    * [ ] Yes
    * [x] No
    * [ ] Maybe so

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
# Pull Request

## Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder-docs/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 4.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Adds a warning to remind users to not load `.spydata` data unless they created it themselves, or they verifiably trust its source, since it inherently runs untrusted code.

### Issue(s) Resolved

Fixes #328

### CODE REVIEW

**Review by jitseniesen — APPROVED** [review]
Looks good to me. I am not overly keen on your use of "verifiably", but that's not important.

**Comment by CAM-Gerlach** [comment]
Yeah, I'm not super solid on that particular word either—any alternate suggestions? Or, should I just elide it?

**Comment by jitseniesen** [comment]
I would remove it, but if you feel it should be stronger than just "trust", how about "fully trust" or "completely trust"?

**Comment by CAM-Gerlach** [comment]
Yeah, my intent there was to emphasize that users should not only think they trust it, but also verify that they did so—the old "trust but verify" (since users may implicitly trust that, e.g., an email came from a close college, when it in fact was phishing, spoofing, a hacked account, etc). But I'm not sure that comes across clearly. In any case, I changed it to "fully" :+1: .

**Pull request merged**
