### PR TITLE
PR: Update logo across documentation

### PR DESCRIPTION
**Pull request by isabela-pf**
# Pull Request

## Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 4.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

This PR replaces logo image files used in the docs with the new logo. Please let me know if anything looks wrong.

Logo changes across the project, motivation, and voting can be tracked on [spyder #13181](https://github.com/spyder-ide/spyder/issues/13181) and [ux-improvements #50](https://github.com/spyder-ide/ux-improvements/issues/50).

I've yet to replace `index-docs.gif` because I am not sure if there is a specific way you'd like that page to be scrolled. I can add this if wanted.

## Issue(s) Resolved

Fixes [spyder #13181](https://github.com/spyder-ide/spyder/issues/13181)

### CODE REVIEW

**Comment by isabela-pf** [comment]
I removed `spyder_logo_docs.png` and `spyder_logo_lightbg_text_left.png` based on feedback that they were not being used in the docs.

`readme_banner.png` now uses Raleway Semibold to match the typeface used in the docs and website.

**Comment by isabela-pf** [comment]
The failing check says it's reacting to a broken link, but it looks like a link that has nothing to do with any of my changed files. Am I misunderstanding, or is there something I missed in this PR?

**Comment by juanis2112** [comment]
You are right! I will push a commit fixing this link in this PR since otherwise you would have to rebase once I fix it and it is a simple change.

**Review by ccordoba12 — APPROVED** [review]
Thanks @isabela-pf!

**Pull request merged**
