### PR TITLE
PR: Update all screenshots to high-res versions from Spyder 3.2.8 and Win10, and add new ones

### LINKED ISSUE #14: Update screenshots to those from modern Spyder, and add additional shots of different Main Window layouts, etc
## Issue Description

Many of the screenshots we currently have are from very old versions of Spyder, running on vintage OS versions and have a lot of chrome around the actual content. This is both potentially inaccurate and confusing to our current users, and does not present a good impression to potential new ones. Therefore, this should be speedily corrected before the initial public release.

As part of spyder-ide/spyder-website#75 I will be taking some screenshots anyway, so I may as well hit on what is needed here. Specific work items:

- [ ] Add "default" master screenshot to Index and Overview pages
- [ ] Add ~3 additional screenshots with various panel, layout, and color arrangements to the Overview page
- [ ] Add/update panel screenshots for each respective page
- [ ] Maybe add a few specific install process screenshots or other graphics to installation document?

### Where is the relevant portion of the documentation located?

Primarily in the sections on the core/older features, such as the editor and console, and in sections not referring to a specific feature.

### What would you suggest it be replaced with?

More and better screenshots from modern Spyder.

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Adds over 200 new, consistent, high-resolution screenshots of modern Spyder (3.2.8) running on a clean Win 10 test machine, replaces all the existing old screenshots and adds a few new ones where appropriate and called for by the existing text, minor layout alterations to the text and theme to accommodate the new images. Also, removes the obsolete legacy console docs (to remove the need to update the now non-existant image) and update links to point to the IPython Console, merging a short paragraph from the former into the latter.

Hopefully this can get reviewed promptly, as I can really get started on whipping the existing text/content into some semblance of shape to address #13 and #15 (updating/correcting out of date/innacurate content, copyediting, adding low-hanging fruit, etc) until this gets merged. I tried to make it as straightforward and non-controversial as possible, just direct replacements of the existing screenshots and a few very judicious new ones as previously discussed, and essentially no real changes to the actual body text itself, so hopefully that can happen quickly. Thanks.

### Issue(s) Resolved

Fixes #14

### CODE REVIEW

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I think we should use Git LFS in this repo to handle images, given the sheer amount of them you want to commit in this PR. So my advice is to close this PR, remove/recreate your local clone (so you can't inadvertently add these images in another PR) and start again with Git LFS and a PR that only adds the updated images required by our current docs.

After that, please open new PRs, each with a single (no matter if short or long) change to our docs and the new images required by it. Does that sound like a good plan?

**Comment by ccordoba12** [comment]
> From what I've read and heard about it, git LFS (Large File Storage) seems to be designed to handle versioning very large individual files

The thing is this: git-lfs is not only good to handle large files, but binary files in general, so that they don't become part of git history.

That way, fetching, cloning and pushing to this repo will take much less time, so it'll be easier to work with it.

> I'm a little confused as to the point of this step too, sorry—if they're still hanging around on my local repo, then they'll still be on my fork that I reclone the repo from, unless I'm silly enough to just leave them untracked in the working dir for some reason. What am I missing?

The problem is you could add (by mistake) this PR to git history and that would make git-lfs useless.

> If the other images aren't in the repo and instead siloed away somewhere on my disk or on Google Drive, anyone else but me who wants to add to, enhance or fix issues with the docs won't have access to them, resulting in either duplicated effort to take likely less consistent/high quality screenshots, or other users' contribution lacking them altogether and having to manually go through me or a different bespoke/siloed off source to get them, when they could easily just be stored right in the repo that needs them for anyone to use and reference.

What I said is that you should add new images only with an associated PR that requires them. Else, they could end up never been used.

> If you're referring to only updating the currently inserted images in this PR, I actually went back and forth about whether or not to add a few additional ones directly suggested by the current text (and the full window screenshots as discussed) in this PR, or save it for either the next one doing the baseline copyediting, correctness and consistency pass, or the appropriate following one(s) adding basic low-hanging fruit content to specific parts of the docs.

I meant that, for an initial PR, you should only replace our current (and outdated) images. Then, when new text content is added to our docs, you could add more images (as the new content requires them).

**Comment by ccordoba12** [comment]
I don't have much time for these lengthy discussions. So my final proposal is this: let's not use Git LFS, close this PR and start a new PR that only replaces our current images. Then open new PRs to add more images, when new content requires them.

Is that ok for you @CAM-Gerlach?

**Comment by ccordoba12** [comment]
The thing is it would be easier to review and merge PRs that add new images, if we see them in the context of new content being added.

**Comment by CAM-Gerlach** [comment]
> So my final proposal is this: let's not use Git LFS, close this PR and start a new PR that only replaces our current images.

Okay, agreed. That still leaves unresolved the issue of how to make the rest of the comprehensive, standardized screenshot set easily accessible to collaborators other than myself, so they don't duplicate effort for a less consistent result (or fail to include screenshots entirely when existing assets would help illustrate a concept), and I'll need to document the process of finding, selecting, and adding them, but we can finishing hashing that out after we get the initial release out the door—I don't want to hold things up any longer. 

My suggestion here, if we don't want them in the repo, is to recreate the directory hierarchy and upload the screenshots in a subdirectory of our official Google Drive folder that @goanpeca created that we could give view/download access to collaborators interested in working on the docs. They'd then need to preview them on there, and download and copy them over into the/a corresponding subdirectory of ``images`` if they wanted to add them to a content section; we'd need to add information on this process to the Contributing Guide. Relative to just sticking them in the repo, this makes for an overall more manually-tedious and time intensive workflow and an extra layer of complexity for the gain of at most a few seconds when ``push`` ing and , but still better than Git LFS in both regards and less of a potential for more serious and intractable problems.

**Comment by ccordoba12** [comment]
> My suggestion here, if we don't want them in the repo, is to recreate the directory hierarchy and upload the screenshots in a subdirectory of our official Google Drive folder that @goanpeca created

There's no problem with having them here. In fact, I think it's better. I was just worried about that making it difficult to work with the repo. But that doesn't seem to be the case.

**Comment by CAM-Gerlach** [comment]
> There's no problem with having them here. In fact, I think it's better. I was just worried about that making it difficult to work with the repo. But that doesn't seem to be the case.

Okay, cool beans. So, with that being the case then, do we want to:

1. Re-open this one after all and go from there, since that's essentially what this PR does (fastest solution and allows easy adding of images to the visible doc content, which could then be reviewed in context and in smaller chunks, as you requested, in the more narrowly scoped future PRs that actually use them in the text)
2. Rebase it (here or in a copy of this branch/PR) to only add the images that are actually used with the current content, and then add the rest in a followup PR (modest time needed, and could be deferred until after the initial public release, but it would get messy if we wanted to add any other new images not in this one until after it is merged)
3. Just doing the first part of 2. and not adding the images until they are needed (your previous request, which I was just starting to implement, but that would contradict you just said about wanting to include them in the repo after all as the best option with the disadvantages I cited)

Let me know which one you'd like—they're arranged in order of preference, but I'll go right ahead with whichever you think best. Just say the word—err, the number. Thanks!

**Comment by ccordoba12** [comment]
Using this PR will mess with git history (due to the large addition and removal of files), so please create a new PR instead.

**Comment by ccordoba12** [comment]
A new PR from scratch, I meant.

**Comment by CAM-Gerlach** [comment]
So which option? Option 2. in a new branch and a new PR based off this branch with the extra files interactive ``rebase``d out (i.e. replacing the first commit from scratch with just the needed files, and then replaying the other commits on top of that, so that the other never existed in that branch)? And then another followup PR with the rest of the files, which can then be reviewed in detail as you requested when they actually get added to user visible content in individual content-specific PRs?

**Comment by CAM-Gerlach** [comment]
To be honest I'm not still sure what we really gain from adding the rest of the files all a separate PR, other than extra work rebasing and reorganizing everything and the possibility to defer merging of that for a bit longer...

**Comment by ccordoba12** [comment]
> So which option? Option 2. in a new branch and a new PR based off this branch with the extra files interactive rebased out (i.e. replacing the first commit from scratch with just the needed files, and then replaying the other commits on top of that, so that the other never existed in that branch)? 

Yes, that's it.

> To be honest I'm not still sure what we really gain from adding the rest of the files all in a separate PR

A couple of things:

1. For us reviewers, we'll see what images are going to be added for new content.
2. To not leave unused images here. Maybe you get busy in the future, and you don't have time to write all the new content you have planned right now.

**Comment by CAM-Gerlach** [comment]
> Yes, that's it.

Sorry for the continued confusion, but I thing there was a miscommunication somewhere, since both of the valid concerns you list under

> A couple of things

are only directly addressed with Option 3, since Option 2 (as noted in both my previous posts) would then add all the rest of the images to the repo in a separate followup PR (as mentioned previously, Option 3 is basically just your "final proposal" above). I was going to implement the latter, but then you said, in reply to my suggestion of where to put the full set of screenshots for others to use since we weren't putting them in the repo,

> There's no problem with having them here. In fact, I think it's better. 

...which is what 1. and 2. propose, whereas 3. (your previous proposal) would essentially require the full set of screenshots stored somewhere externally and then manually copied into the correct hierarchy if another collaborator wants to use them, with the disadvantages that entails as mentioned in my previous post that you were responding to.

> For us reviewers, we'll see what images are going to be added for new content.

True. But won't you see them either way, and in context, when you're reviewing the changes that actually add them?

> To not leave unused images here. 

Indeed, and it could be some work tracking down which are used or not.

> Maybe you get busy in the future, and you don't have time to write all the new content you have planned right now.

This is actually the main reason behind adding to the repo, so they're readily accessible to contributors other than myself. Otherwise, we have to set up a bespoke system to store them (like the Google Drive solution I suggested) and individually invite interested collaborators, which is more of a burden and increases the barrier to entry for new potential contributors.

So, at least how I see it, it basically comes down to a cost-benefit between maintaining a separate shared google drive folder with the full set of screenshots (and any more that aren't used right away), vs. just including them in the repo; the former keeps the repo itself somewhat faster and cleaner (at least until most of them are added), and makes reviewing potentially a little easier, at the cost of some more time and tedium for collaborators both up front and on an ongoing basis, as well as being another potential hurdle for new contributors.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I really can't keep discussing about this, sorry. Please don't take this the wrong way, it's just that I see things very simple but it seems I'm unable to convey to you what I want :-)

So I'll do a PR for you, committing on your behalf, and I'll submit it as soon as I can (a couple of days at most).

**Comment by CAM-Gerlach** [comment]
I can just go ahead with what you previously said as your "final proposal" in [this comment](https://github.com/spyder-ide/spyder-docs/pull/22#issuecomment-386923816), as that part was indeed clear and simple and it seems that's still what you want as a first step. We can worry about where to host the rest of the images after, and it seems that's where the confusion/misunderstanding came in.

**Comment by ccordoba12** [comment]
Thanks a lot for understanding! I think our purpose for an initial public release is to iterate as quickly as we can until we have something decent to show to the world (like we did with the homepage).

After that, we can discuss about the fine details of future additions.

**Comment by CAM-Gerlach** [comment]
That's the plan!

**Pull request closed without merging**
