### PR TITLE
PR: Replace files gifs in docs for Spyder 5

### PR DESCRIPTION
**Pull request by juanis2112**
# Pull Request

## Pull Request Checklist

* [ ] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [ ] Based your PR on the latest version of the correct branch (master or 4.x)
* [ ] Checked your writing carefully for correct English spelling, grammar, etc
* [ ] Described your changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed

## Issue(s) Resolved

Fixes #

### CODE REVIEW

**Comment by ccordoba12** [comment]
@juanis2112, it seems you forgot to update `files-commit.gif` for Spyder 5. The rest looks good to me.

**Comment by juanis2112** [comment]
I couldn't fix it since it is not working. I opened an issue about it https://github.com/spyder-ide/spyder/issues/15458

**Comment by ccordoba12** [comment]
I fixed that error in PR https://github.com/spyder-ide/spyder/pull/15895. So now you can update that gif.

**Comment by juanis2112** [comment]
Updated the gif! @ccordoba12

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @juanis2112!

**Pull request merged**
