### PR TITLE
PR: Add banner for out of date and development versions

### LINKED ISSUE #188: Add version banner on older or dev versions with link pointing to current stable
We don't need to do this right away, but @dalthviz suggested I open an issue so as we don't forget. One approach to doing so is described [in the Sphinx-Multiversion docs](https://holzhaus.github.io/sphinx-multiversion/master/templates.html#version-banners)

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
# Pull Request

## Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 4.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Adds an alert banner to the top of the docs for development (currently just feature branches, but will include `master` assuming we branch `5.x` before Spyder 6 is released) and outdated (Spyder 3, Spyder 4) versions that states this and links to the latest supported stable version.

Requires spyder-ide/spyder-docs-sphinx-theme#44 (which in turn is waiting on spyder-ide/spyder-docs-sphinx-theme#43 ) to be merged and the temp commit dropped before merging, but those both should hopefully be merged very soon.

## Issue(s) Resolved

Fixes #188

### CODE REVIEW

**Comment by juanis2112** [comment]
Right now this is for master branch if  I understand correctly? But not sure why we need to say this if spyder 5 docs are almost ready.

**Comment by CAM-Gerlach** [comment]
@juanis2112 Actually, this is primarily for development and outdated versions of _Spyder_, rather than directly related to the development status of the docs themselves, to let people know that they are using the docs for an outdated version, or an unstable development version (once we branch the `5.x` docs and start the docs for Spyder 6) that is not yet the current stable, and offering a direct link to the current version of the same page. This is what most other projects do, and matches the example shown in the sphinx-multiversion docs.

Ideally, we'd keep the dev status of Spyder and its docs roughly in sync (at least in terms of major releases). However, these improvements allow us to customize the docs banner to say whatever we want (or not appear at all) on specific version(s), so the message could be changed to refer to the development status of the docs too (or even add a separate one), but as you say, no real need for that right now.

**Comment by juanis2112** [comment]
Oh got it. Sorry for the confusion. This is fine then

**Review by juanis2112 — APPROVED** [review]

**Comment by CAM-Gerlach** [comment]
Thanks for the review, @juanis2112 . Merging.

**Comment by CAM-Gerlach** [comment]
Thanks for the review, @juanis2112 . This is currently blocked on the trivial spyder-ide/spyder-docs-sphinx-theme#44 being merged, if you wouldn't mind approving that.

**Comment by CAM-Gerlach** [comment]
spyder-ide/spyder-docs-sphinx-theme#44 was merged, so this is ready to go. I'll implement a more reliable fix to the flaky Gentoo link in my next PR, which among other thing backports the pre-commit, build, CI and linkcheck fixes, upgrades and improvements made in `master` and other repos to `4.x`.

**Pull request merged**
