### PR TITLE
Remove Curlylint, add Black and fix ESLint

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
# Pull Request

## Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder-docs/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 4.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below

## Description of Changes

Followup from #383 and #384 , removes the unused, unmaintained and slow Jinja template linter Curlylint, adds the code formatter Black and applies the latter to blacken the repo's Python scripts (excluding the examples in the `/workshops` subdirectory). Additionally, adds a custom `.black.toml` config file to avoid adding an unnecessary, inappropriate and potentially misleading `pyproject.toml` to this repo that's not any form of Python package.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Seems like there's a strange, hopefully temporary dependency conflict issue trying to install eslint (never seen that before), so hopefully that'll result itself in a day or two; there's no rush to merge this immediately.

**Comment by CAM-Gerlach** [comment]
Welp, seems like the strange NPM dependency conflict that suddenly popped up has still not been resolved, so I'll dig in and investigate it myself.

**Comment by CAM-Gerlach** [comment]
Welp, after several hours investigating, I reported this as eslint/eslint#18956 , and appears to be solved by eslint/eslint#18945 and was able to drill down to a workaround for now. Unfortunately, pinning the specific problematic dep didn't work for some reason, so I had to pin ESLint on a modestly older version for now until that's released.

**Review by ccordoba12 — COMMENTED** [review]
Looks good to me, but I think one thing is missing before merging: we should add commit 9e75d1834b30a486e6b8d0a011be43b587e8cd2d to `.git-blame-ignore-revs` so that it's ignored by `git blame`.

That's the recommended approach when applying Black to a repo and I think it's a good idea.

**Comment by CAM-Gerlach** [comment]
Okay, sure; I didn't add that before since the blackening only affects a couple scripts, and users need to either manually pass the path to that file every time, or (in recent-ish Git versions) manually configure Git to set and use this as the ignore file. However, after thinking about it a bit, I realized I can just add that to the things the `setup` command does, which I did so.

I also noticed and fixed a small perf issue in `setup-remotes`.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @CAM-Gerlach!

**Pull request merged**
