### PR TITLE
PR: Consistent look and feel with the rest of the website

### LINKED ISSUE #19: Add the same banner used in the website and use the same fonts in its content
We need this to have a consistent look and feel between the other pages in the site and our docs.

@dalthviz, please work on this one. For the fonts, please use *Amiri* for headers and *Raleway* for content.

### PR DESCRIPTION
**Pull request by dalthviz**
### Pull Request Checklist

*  [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
*  [x] Based your PR on the latest version of the correct branch (master or 3.x)
*  [x] Checked your writing carefully for correct English spelling, grammar, etc
*  [x] Described your changes and the motivation for them below
*  [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

- [x] Change fonts (`Amiri`, `Raleway`).
- [x] Change color of links `#EE1C24`.
- [x] Add banner/navbar.

Following the issue to resolve.

### Issue(s) Resolved

Fixes #19 

### Preview

imagen

### CODE REVIEW

**Comment by ccordoba12** [comment]
CAM, Amiri is currently used in the headings of our blog. I think it looks really good there, but not in the front page. That's why I removed it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Ah, I see—I didn't think to check the blog separately, sorry. 

In any case, I guess it works okay there, but I would greatly prefer the sans font from the mainpage for the headers (or similar) for several additional reasons: 

* A serif font like that one communicates the feel of being stuffy, staid and dated rather than clean, modern and approachable as our documentation should be.
* It looks much more consistent with our main page, as you pointed out
* Looking at peer examples, every flagship project I could find—numpy, scipy, jupyter notebook/jupyterlab, matplotlib, IPython, pandas, and particularly sphinx itself all uses sans fonts for headers, the latter even a very similar one to our mainpage
* It introduces another font into a page that already has at least two (the text and the logo), along with a number of different faces/styles, increasing visual clutter and decreasing coherency
* From a personal taste point of view, it just looks better and cleaner overall, while the serif one looks somewhat out of place IMO

**Comment by ccordoba12** [comment]
@dalthviz, could you update the screenshot with your latest changes? Thanks!

**Comment by dalthviz** [comment]
Hi @CAM-Gerlach about your comments:

> Banner looks good, except for that its a little bit bigger than the blog and main site (and than it needs to be) in height and font size. I assume you'll backport the small caps to the other two? Also, should we try to match the width of the banner (between the left margin of the logo and the rightmost "docs" text) with the width of the docs and blog pages, so they fit better? Or is keeping perfect continuity with the main page more important?

I'm not quite sure to see the differences in height and font-size between the docs banner and the banner in the blog or main page (for all is set to 13px the font-size I think). So could you take some screen shots to see the differences. Also yep, I will do the cap of the `S` in the banners of the other pages. About the width between the ends of the banner (logo and docs), I'm not sure, what do you think @ccordoba12 ?

And thanks for the feedback :+1:

and @ccordoba12 a preview
imagen

**Comment by CAM-Gerlach** [comment]
> I'm not quite sure to see the differences in height and font-size

You are indeed quite right;; there is no different in height—I'm not sure what I was thinking, sorry. The difference in the apparent font size is due to the existing word mark being "lowercase" small caps, while the new one on the docs has the full height uppercase "S", making the apparent font size larger. Once you backport that change, they should presumably be identical.

> About the width between the ends of the banner (logo and docs), I'm not sure

I'm not 100% sure about this either, since the blog isn't exactly the same width as the docs either and is adaptive.

**Comment by CAM-Gerlach** [comment]
Thanks @dalthviz . The font size looks much better now, IMO, and the other changes look good. You can probably just remove the logo from the sidebar entirely since it is basically redundant with the top bar logo/text just above it, and also makes changing the width later more annoying. Of course, I'm still a strong -1 on the serif font for headings instead of using the existing sans like the mainpage, but that's awaiting @ccordoba12 's opinion.

**Comment by dalthviz** [comment]
A new preview

imagen

@CAM-Gerlach again thank you for your feedback :+1:. Also, something that only until now I realised was the missing `Fork me on Github` link. I added it again :)

**Comment by ccordoba12** [comment]
@dalthviz, things are looking really good! Some comments:

1. Please remove again the *Fork me on Github* label. It looks odd.
2. Remove the *Star* count and the *build* badge present on top of the table of contents. It makes little sense to show them as part of our docs.

After those changes, I think this one would be ready.

@CAM-Gerlach, let us play for a bit with the Amiri font. I think it looks really well on headers, but we can remove it later if it doesn't fit with our docs.

**Comment by dalthviz** [comment]
A new preview:

imagen

**Comment by dalthviz** [comment]
A new preview:

imagen

imagen


@CAM-Gerlach about the `font-size` I think that definitely we have to decide the standard size (in comparison with the current size here, the size in the blog now looks kind of big). What do you think @ccordoba12 ?

**Comment by CAM-Gerlach** [comment]
@dalthviz Fantastic, thanks. Not to keep bugging you, but the Navigation still isn't exactly the correct size; right now its 33.6px while the main heads are 37px.

Now that I look more at it, IMO probably the best solution is to bump the doc font up one more size to 16.8px, and bump the blog down one to that as well. It should be a good compromise between the two, and will also match the sidebar main font size as well. Accordingly, the top/main and sub heads of the blog could also be brought down to 37px and 27.7px from 48px and 39.6px respectively to match as well, as they are quite big as is, although both could be brought to a size a little bigger than the current docs if the latter is a bit too small for all purposes.

**Comment by ccordoba12** [comment]
> I think that definitely we have to decide the standard size (in comparison with the current size here, the size in the blog now looks kind of big). What do you think @ccordoba12 ?

I'd say we should merge this one so we can take a look at both pages at the same time.

@CAM-Gerlach, could you approve so we can keep iterating? Thanks!

**Comment by ccordoba12** [comment]
@dalthviz, please also open a new PR in our website repo to add the *Docs* link to its navbar.

**Comment by CAM-Gerlach** [comment]
> I'd say we should merge this one so we can take a look at both pages at the same time.

Just FYI, if you pull the branch then run ``make html`` from the ``doc`` directory, you can open it in a web browser and it'll look exactly like as if it was deployed live.

> @CAM-Gerlach, could you approve so we can keep iterating? Thanks!

Yup, will do now.

**Pull request merged**
