### PR TITLE
Update channel in install commands from spyder-ide to conda-forge

### PR DESCRIPTION
**Pull request by P-Tillmann**
## Description of Changes
Update channels for install instructions of spyder plugins

### Issue(s) Resolved

Resolves [GHI343](https://github.com/spyder-ide/spyder-docs/issues/343)

### CODE REVIEW

**Review by CAM-Gerlach — COMMENTED** [review]
LGTM, but looks like there's one other instance:

```
HEAD:doc/faq.rst:      conda install -c spyder-ide <PLUGIN>
```

Thanks!

**Comment by P-Tillmann** [comment]
Hi @CAM-Gerlach, thanks for pointing out the FAQ. I updated it there as well.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM, thanks @P-Tillmann !

**Comment by CAM-Gerlach** [comment]
Also, just FYI—it seems you made this PR from the `master` branch of your fork instead of a feature branch. To avoid issues in the future, ensure you always make your changes in a new feature branch (as [our Contributing Guide details](https://github.com/spyder-ide/spyder-docs/blob/master/CONTRIBUTING.md#making-your-changes)), and to fix the current problem, either delete your fork (and recreate it if desired), or run the following commands locally (assuming `origin` is your fork and `upstream` is this repo, per standard convention and [our contributing guide](https://github.com/spyder-ide/spyder-docs/blob/master/CONTRIBUTING.md#fork-and-clone-the-repo):

```shell
git switch master
git fetch --all
git reset --hard upstream/master
git push --force origin master
```

**Pull request merged**
