### PR TITLE
PR: Don't show plugins in index that aren't yet compatible with Spyder 5

### PR DESCRIPTION
**Pull request by juanis2112**
# Pull Request

## Pull Request Checklist

* [ ] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [ ] Based your PR on the latest version of the correct branch (master or 4.x)
* [ ] Checked your writing carefully for correct English spelling, grammar, etc
* [ ] Described your changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Removed plugins index from docs for spyder 5 until all the plugins are migrated and compatible with Spyder 5.

## Issue(s) Resolved

Fixes #

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Are some of the plugins compatible yet? If so, it makes sense to still include the plugin index, and instead move the incompatible plugins to a comment in `indexplugins.rst`. Also, I wouldn't suggest waiting until "all" of the plugins are compatible, and rather simply add each plugin as it is updated (and some might never be). No reason to hide documentation for the working plugins, only the non-working ones.

**Comment by ccordoba12** [comment]
> Are some of the plugins compatible yet?

Only Spyder-terminal, but I think @juanis2112's idea is to update all plugin docs at the same time.

> and instead move the incompatible plugins to a comment in indexplugins.rst

That's a good idea. @juanis2112, what do you think?

**Comment by CAM-Gerlach** [comment]
> Only Spyder-terminal, but I think @juanis2112's idea is to update all plugin docs at the same time.

Yeah, but that means that all the plugin docs are blocked on the slowest to migrate plugin, instead of being added whenever the plugin gets migrated. IMO, if and when a plugin is supported, I'd favor making its docs available immediately, with any changes necessary so that the basic instructions are accurate for Spyder 5. If doing the updated screenshots and such is the blocker, that can be deferred, as we did for the Spyder 4 docs, as its better to have working docs with slightly out of date screenshots than no docs at all, assuming the plugin is compatible.

**Comment by juanis2112** [comment]
I think however you think is best is fine for me @CAM-Gerlach. Do you want to do the change?

**Comment by CAM-Gerlach** [comment]
> Do you want to do the change?

Sure.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM now, thanks. @juanis2112 All good to merge?

**Comment by CAM-Gerlach** [comment]
Rebase complete; trivial PR, preview looks good and we all agree on how we want this to look, so going ahead and merging.

**Pull request merged**
