### PR TITLE
PR: Replace screenshots in troubleshooting guide for Spyder 5

### PR DESCRIPTION
**Pull request by juanis2112**
# Pull Request

## Pull Request Checklist

* [ ] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [ ] Based your PR on the latest version of the correct branch (master or 4.x)
* [ ] Checked your writing carefully for correct English spelling, grammar, etc
* [ ] Described your changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed

## Issue(s) Resolved

Fixes #

### CODE REVIEW

**Review by ccordoba12 — CHANGES_REQUESTED** [review]
@juanis2112, most of my comments below don't correspond to screenshots, but we can take the opportunity to fix those minor things.

* In this section

    http://docs.spyder-ide.org/current/troubleshooting/emergency-cpr.html#common-solutions

    please change the text above the `emergency-cpr-single-instance.png` image to mention that the single instance option is present now in `Application`. In Spyder 4 that was in `General > Advanced Settings `.

* In the Spyder/Spyder-kernels table in this section

    http://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-not-installed-incompatible

    please add that from versions `5.0.0-5.0.5` of Spyder, you can use Spyder-kernels `2.0.1-2.0.5`.

* `common-illnesses-atribute-error.png` is not updated for Spyder 5. If you need help to fake that error (I think it's hard to reproduce it these days), please let me know.

* `common-illnesses-missing-docstring.png` is not updated to Spyder 5.

**Comment by juanis2112** [comment]
Thanks @ccordoba12. I will fix them. I do need help with both common-illnesses-atribute-error.png and common-illnesses-missing-docstring.png

**Comment by juanis2112** [comment]
Fixed all your suggestions @ccordoba12

**Review by ccordoba12 — APPROVED** [review]
Thanks @juanis2112 for the improvements! Now things look good to me.

**Pull request merged**
