### PR TITLE
PR: Overhaul index page with new and updated content for Spyder 4

### PR DESCRIPTION
**Pull request by juanis2112**
### Pull Request Checklist

* [ ] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [ ] Based your PR on the latest version of the correct branch (master or 3.x)
* [ ] Checked your writing carefully for correct English spelling, grammar, etc
* [ ] Described your changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

1. Changed main window screenshot for dark theme one
2. Added description of sections in docs
3. Added community section with useful resources

Screen Shot 2020-07-03 at 11 35 36 PM
Screen Shot 2020-07-03 at 11 35 40 PM
Screen Shot 2020-07-03 at 11 35 46 PM
Screen Shot 2020-07-03 at 11 35 59 PM

### Issue(s) Resolved

Fixes #

### CODE REVIEW

**Comment by juanis2112** [comment]
@ccordoba12 and @CAM-Gerlach I made the changes we talked about in the meeting. Not sure how to align the icons for the community section with the titles but I'm sure we can do that in css when we merge the theme. Please take a look at the content and let me know any comments you have!

**Comment by juanis2112** [comment]
@ccordoba12  I agree. I like this one

user-friends-solid7

But here are some other options so you can pick from here if you like some other color better:

user-friends-solid5
user-friends-solid4
user-friends-solid6
user-friends-solid3
user-friends-solid2
user-friends-solid1

**Comment by ccordoba12** [comment]
> But here are some other options so you can pick from here if you like some other color better:

Thanks @juanis2112! I like this one more:

imagen

but please don't change it for now. We'll see how it looks directly on the page in our meeting tomorrow.

**Comment by CAM-Gerlach** [comment]
I prefer @juanis2112 's suggestion, but I don't have a particularly strong opinion.

**Pull request merged**
