### PR TITLE
Remove references to PyQt4 because it's going to be deprecated in Spyder 3.3

### PR DESCRIPTION
**Pull request by ccordoba12**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Accompanying PR for spyder-ide/spyder#6991.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Hey, so all of this is already implemented in my baseline-pass branch to fix #13 , as noted in the review comment. Sorry for the duplicated effort! You can create a separate issue to track it if you want which my #13 PR can close.

**Comment by ccordoba12** [comment]
> Hey, so all of this is already implemented in my baseline-pass branch to fix #13

I thought you were going to implement it, not that you already did! No problem then, I'll close this one and open am issue to be referenced in #13.

**Comment by CAM-Gerlach** [comment]
Sorry about that—that's what I get for sitting on a big, monolithic, conflict-happy PR for too long. However, a lot of the reason it is monolithic and would cause lot of conflicts if I broke it up is due to implementing a consistent style guide across all files to make editing and reviewing much easier, more modular and less likely to cause conflicts in the future (particularly, breaking lines by sentence instead of hard-wrapping at a fixed character count, to prevent small changes from cascading to multiple lines) and prevent us from ever needing to do such a large, multi-file PR again after this public release; everything can be in nice, small, single-file PRs that can get reviewed and merged quickly and coexist in peace :)

**Comment by ccordoba12** [comment]
No worries, but we need your fixes soon (a week and a half, two weeks at most), so we can have our new docs ready for 3.3 :-)

**Pull request closed without merging**
