### PR TITLE
PR: Add docs for Spyder Notebook

### LINKED ISSUE #137: Write docs for Spyder Notebook
### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

### PR DESCRIPTION
**Pull request by gsg001**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Checked your writing carefully for correct English spelling, grammar, etc
* [x] Described your changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed

## Description of Changes

Add a new doc for Spyder Notebook.

### Issue(s) Resolved

Fixes #137

### CODE REVIEW

**Comment by jitseniesen** [comment]
Awesome, I was thinking a couple of hours ago that we really should have some documentation on the notebook plugin and here is already a first stab at it!

**Comment by jitseniesen** [comment]
@gsg001 Are you planning to continue working on this? I am quite keen to see some documentation for the Spyder notebook plugin, as I am planning to release a new version soon.

**Comment by juanis2112** [comment]
Hi @jitseniesen, if @gsg001 doesn't reply, I'm happy to finish this PR. However if you are going to release a new version soon, maybe we should wait for the release in order to update the screenshots to match this new version. Do you agree?

**Comment by jitseniesen** [comment]
>  I'm happy to finish this PR. However if you are going to release a new version soon, maybe we should wait for the release in order to update the screenshots to match this new version. Do you agree?

I agree that the screen shots should use the new version, but I don't expect that the screen shots will change from how they are now. In any case, there is some work to be done on the text. I can also take care of this, you don't have to do all the work.

**Comment by juanis2112** [comment]
@jitseniesen will you include the dark theme for this new release? I think we should give @gsg001 a few more days to see if he wants to finish this and if not we can go ahead and finish it. Maybe you can help reviewing the text and then @CAM-Gerlach can take care of the format while I can work on the screenshots and some gifs where needed. Let me know what you think about this.

**Comment by jitseniesen** [comment]
Yes, the new release will include the dark theme, so it will look quite different. I agree, let's wait a few more days.

**Comment by gsg001** [comment]
Sorry, I got busy with summer holidays and the kids. I am planning on working on this next week.

**Comment by CAM-Gerlach** [comment]
No worries, thanks @gsg001 ! Looking forward to seeing what you come up with!

**Comment by juanis2112** [comment]
Thanks @gsg001, let us know if you need any help!

**Comment by juanis2112** [comment]
Hi @gsg001  I think @CAM-Gerlach and I will finish this PR!

**Comment by jitseniesen** [comment]
Great! Ping me when you need some help or want me to read over something.

**Comment by juanis2112** [comment]
Closing this one because it will be replaced by this one #264

**Pull request closed without merging**
