### PR TITLE
PR: Tweak sidebar font size and line height to match revised doc content style

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] ~~Checked your writing carefully for correct English spelling, grammar, etc~~
* [x] Described your changes and the motivation for them below
* [x] ~~Noted what issue(s) this pull request resolves, creating one if needed~~

## Description of Changes

The content body, header, and line spacing font parameters were changed in the recent series of PRs superseding #48 ; however, unlike in that PR, the corresponding sidebar sizes were not adjusted accordingly. Therefore, this PR ports over those changes—namely, setting the proper body, heading, and line-height sizes in the sidebar relative to the body text—as well as taking the opportunity to do a bit of minor cosmetic cleanup and consolidation in ``custom.css``.

### Issue(s) Resolved

N/A; minor followup to earlier PRs

### CODE REVIEW

**Comment by ccordoba12** [comment]
>  however, unlike in that PR, the corresponding sidebar sizes were not adjusted accordingly

It seems you're trying to make the sidebar to have the same font size and other features of the main text. If that's the case, I don't agree with it because it doens't look good.

I think it's fine for the sidebar to have a smaller font than the main text so users can clearly see the difference between the two.

**Comment by CAM-Gerlach** [comment]
> If that's the case, I don't agree with it because it doens't look good.

What about it doesn't look good, specifically? The l2 links are too small? Navigation heading's too large? Line spacing's too narrow?

Obviously its somewhat a matter of one's own taste in design, but comparing between looks of the current mainline and this branch and ignoring the objective considerations below, my eye sees that latter as subjectively better, with cleaner and more balanced and coherent design.

> I think it's fine for the sidebar to have a smaller font than the main text so users can clearly see the difference between the two.

A basic axiom of good design, one of the very few my mom really drilled into me, is for a clean, professional, non-distracting look focused on the content, one should minimize the number of different font sizes and styles, and if different font sizes *are* used for a good reason, they should be *enough* different that they look clear and purposeful; conversely, if they are too close together they should either be unified or made further apart since it looks sloppy, incoherent and they don't do their job distinguishing the content. 

Right now, the sidebar l1 links (Overview, Installation) and l2 links (page headings) are 16.8 px and 15.4 px, only 0.8 px (+5%) and 0.6 px (-3.75%) away from the body text size of 16 px; this is close enough for neither to be distinctly different from the body text , but far enough to look sloppy and incoherent. Therefore, I bumped the sizes down slightly, to 16px and 15px respectively, so the larger size matches the body text while the smaller is 1 px down (I didn't want to go further to avoid it becoming too small). 

Alternatively, if you think its too small, we could bump the sizes up, to e.g. 18 px and 16 px, but that would make the already large sidebar even larger. We could also do something more radical to make the sizes/styles more distinct from the body text, but I really don't think that's necessary since it is already clearly separated by the larger amount of white space you added (which will likely be increased much further with #63 ), as well as the underline style on all the text and the separate "Navigation" header.

Similarly, the line height is 1.60 (26.8 px) vs. 1.57 (25.1 px) for the body; absolutely no reason to have them different when they are that close since they don't produce a clear visual contrast. Finally, the Navigation heading (24 px) is awkwardly between the sizes of the h2 (25.6 px, +6%) and h3 (20.8 px, -13%) body headings (which are already rather close together) and a tad small besides, so I just bumped it up a tad to match the h2 size.

Incidentally, I just noticed the admonition titles looked a bit large and see that they have the exact same as the current nav header, so I'll fix that momentarily.

**Comment by ccordoba12** [comment]
The sidebar format is adjusted by the theme itself, so I'd prefer to leave it like that. Obviously this is a matter of taste, as you said, but I really don't like your changes, sorry.

**Comment by CAM-Gerlach** [comment]
> The sidebar format is adjusted by the theme itself

To be fair, isn't most of the other things we changed all deviations from the theme? In the [original Alabaster theme](https://alabaster.readthedocs.io/en/latest/) the sidebar main font size is the same as the text size, at least within 0.2 px; the sidebar heading size is matched to the Admonition head size, and in turn the Admonition head size is actually slightly *smaller* than the h3 size (while it is considerably bigger here, since it didn't get bumped down along with the other sans-ified headings in #61 ).

> Obviously this is a matter of taste, as you said, but I really don't like your changes, sorry.

Right, but aside from our offsetting subjective opinions as you mention, there is also the objective principles of design I've cited in favor of the changes.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 However, if neither of those lines of reasoning has much chance of changing your mind on this, then I don't want to waste your time arguing this any further. If that's the case, you can just go ahead and close this, and we can move on. Honestly, if I had to pick only one, #63 (which was directly inspired by your Github Books "counterexample" in another long and stubborn font size discussion) is much more important to the overall look and I'd much rather spend whatever cachet I have in advocating the timely implementation of those changes.

**Comment by CAM-Gerlach** [comment]
I guess I'll just go ahead and close this, since there's been no response for a few weeks.

**Comment by ccordoba12** [comment]
Instead of this, I'd prefer our sidebar to be of fixed size and completely to the left, like the one we talked about in Git books.

However, @dalthviz is quite busy with the ipdb kernel, sorry.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 They are two different changes doing different things for different purposes; this one tweaks the font size to match the main text in order to harmonize the appearance, while that one adjusts the sidebar and body layout and alignment in order to be more responsive to different screen sizes and avoid cutting off the text. However, as mentioned above, I agree the latter is much more important than this, relatively speaking.

**Pull request closed without merging**
