### PR TITLE
PR: Replace Code Analysis gifs in docs for Spyder 5

### PR DESCRIPTION
**Pull request by juanis2112**
# Pull Request

## Pull Request Checklist

* [ ] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [ ] Based your PR on the latest version of the correct branch (master or 4.x)
* [ ] Checked your writing carefully for correct English spelling, grammar, etc
* [ ] Described your changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed

## Issue(s) Resolved

Fixes #

### CODE REVIEW

**Comment by ccordoba12** [comment]
@juanis2112, it seems you forgot to optimize `code-analysis-pylint-disable.gif` and `doc/images/pylint/code-analysis-history-custom.gif`. Could you confirm if that was the case?

If not, I'd say this one is ready to merge.

**Comment by juanis2112** [comment]
Gifs are not being optimised. I'm just reducing the size of the image. However those two are bigger than before because I was using 690px before and now I'm using 720.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. Merging then.

**Review by ccordoba12 — APPROVED** [review]
Thanks @juanis2112!

**Pull request merged**
