### PR TITLE
Documentation for building standalone applications

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

Add documentation for building standalone applications

### CODE REVIEW

**Comment by mrclary** [comment]
I was getting the same error when building the latest commit locally..
```
12:54:01 PM: generating indices... genindex failed
12:54:01 PM: Theme error:
12:54:01 PM: An error happened in rendering the page genindex.
12:54:01 PM: Reason: UndefinedError("'meta' is undefined")
12:54:01 PM: Traceback (most recent call last):
12:54:01 PM:   File "/opt/buildhome/python3.7/bin/sphinx-multiversion", line 8, in <module>
12:54:01 PM:     sys.exit(main())
12:54:01 PM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/sphinx_multiversion/main.py", line 338, in main
12:54:01 PM:     subprocess.check_call(cmd, cwd=current_cwd)
12:54:01 PM:   File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
12:54:01 PM:     raise CalledProcessError(retcode, cmd)
12:54:01 PM: subprocess.CalledProcessError: Command '('/opt/buildhome/python3.7/bin/python3.7', '-R', '-m', 'sphinx', '-D', 'smv_metadata_path=/tmp/tmpaoykbdoj/versions.json', '-D', 'smv_current_version=current', '-c', '/opt/build/repo/doc', '/tmp/tmpaoykbdoj/c77ef4a7f37aef200e4694fea4dd715ecf888698/doc', '/opt/build/repo/doc/_build/html/current')' returned non-zero exit status 2.
```

**Comment by ccordoba12** [comment]
@mrclary, I think this belongs to the [Spyder wiki](https://github.com/spyder-ide/spyder/wiki) and not here. What do you think?

**Comment by mrclary** [comment]
> @mrclary, I think this belongs to the [Spyder wiki](https://github.com/spyder-ide/spyder/wiki) and not here. What do you think?

My principle reservations are the following:
* these instructions are quite lengthy, and I did not think it is appropriate to include them in the main wiki page.
* the main wiki page already directs users to spyder-ide.org for comprehensive instructions for installing Spyder in a myriad of ways.

We could make an additional wiki page for these instructions and reference them on the main wiki page. However, this would not follow the format of the main wiki which directs users to Spyder's main documentation site. Additionally, this would mean having detailed documentation maintained in two separate locations. I thought that the purpose of the wiki of the spyder repository was simply to explain what Spyder is and then direct users to the comprehensive documentation elsewhere.

Regardless, I will do whatever you think is best.

**Comment by mrclary** [comment]
@ccordoba12, additionally, the main wiki page references [Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) which duplicates the Troubleshooting and FAQ pages at https://docs.spyder-ide.org. It seems to me that we should have all the documentation in one place, eliminate the additional wiki page, and change the link on the main wiki page to point to the appropriate location at https://docs.spyder-ide.org

**Comment by mrclary** [comment]
@ccordoba12, okay, I see that wiki is much more comprehensive than I previously realized. I was also using the term "main wiki" when I was referring to the `README.md`.

Since building the macOS application should be considered an action for advanced developers, I think you are correct that it belongs in the wiki. 

However, I still think that the [Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) should be eliminated in favor of the full documentation site. This will eliminate the need to maintain duplicate documentation and reduce confusion for users about where to go.

**Comment by ccordoba12** [comment]
> Since building the macOS application should be considered an action for advanced developers, I think you are correct that it belongs in the wiki.

Great! Thanks for understanding.

> However, I still think that the Troubleshooting Guide should be eliminated in favor of the full documentation site.

Agreed. Could you help us with that? Thanks!

**Comment by ccordoba12** [comment]
I'm going to close this PR given that we agree it doesn't belong here.

**Pull request closed without merging**
