### PR TITLE
PR: Regenerate deploy key and .travis.yml to get CI build working again

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Described your changes and the motivation for them below

## Description of Changes

Somehow the deploy key got removed/deauthed, per the discussion in PR #114 . I regenerated everything, and this should get both the stable and dev builds working (again). No way to test this without merging, so I'll do so once the PR checks pass and hope for the best.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@juanis2112 FYI, the old pylint.org link is broken as the domain is no longer up to date, so I had to update it to get the build to pass. Make sure to run `git rebase master` on your PR #112 to pull the change; it _should_ merge cleanly since the line +/- 1 around it is unchanged, but if not just make sure it is using the modern PyQA link (ironically, when I noticed it was down I actually found a a 2 year old thread started by none other than me myself, likely for the same reason, that explained the situation).

**Comment by CAM-Gerlach** [comment]
@juanis2112 @ccordoba12 @goanpeca I have the distinct pleasure of informing you all that deployment is now working again and the develop version of the docs site is now up and running at [docs.spyder-ide.org/develop/](http://docs.spyder-ide.org/develop/). Check it out!

**Comment by juanis2112** [comment]
@CAM-Gerlach Thank you very much for working on this! It looks great.

**Comment by jitseniesen** [comment]
Great stuff! The development branch looks much better than the stable branch in many places, leaving me to wonder why it does not simply overwrite the "production" website. Was this a conscious decision?

**Comment by ccordoba12** [comment]
> Was this a conscious decision?

Yes. There are two main reasons for this:

1. We're working with @dalthviz to create a new Sphinx theme for our docs website.
2. There are still a lot of panes whose docs that haven't been updated yet. So right now we have a mix of Spyder 3 and 4 docs, which could be very confusing to our users.

**Comment by dalthviz** [comment]
Just in case, 
* This is the repo of the new theme: https://github.com/spyder-ide/spyder-docs-sphinx-theme/tree/develop_spyder
* This PR shows an example of theme: https://github.com/spyder-ide/spyder-docs-sphinx-theme/pull/3

**Pull request merged**
